blank_issues_enabled: false
contact_links:
  - name: Map Database / Warzone 2100 Issues
    url: https://github.com/Warzone2100/warzone2100/discussions
    about: Please ask and answer questions here.
